"""Context summarization for codebase-related queries and debugging.

This module implements a specialized assistant that organizes and summarize all the
KnowledgeGraph traversal context into a single summary.
"""

import logging
from typing import Sequence

from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.messages import AIMessage, BaseMessage, HumanMessage, SystemMessage, ToolMessage

from prometheus.lang_graph.subgraphs.context_provider_state import ContextProviderState


class ContextSummaryNode:
  """Organizes and presents comprehensive code context for debugging and understanding.

  This class processes and structures code-related context retrieved from knowledge
  graph searches, maintaining complete technical details while organizing information
  in relevance layers. It preserves all potentially relevant information including
  implementation details, configurations, and documentation.
  """

  SYS_PROMPT = """\
Present ALL relevant code context exactly as follows:
1. File path
2. Line range
3. Complete code with line numbers in format: 
   <line_number>: <code_line>
4. Complete dependency chain

CRITICAL:
- Include line numbers for ALL code snippets
- Show COMPLETE file contents
- Present EXACT implementation details
- Provide ALL context AS-IS

YOU SHOULD ONLY PROVIDE THE RELEVANT CONTEXT, NOTHING ELSE
  """

  HUMAN_PROMPT = """\
The user query is: {query}

The retrieved context from another agent:
{context}
"""

  def __init__(self, model: BaseChatModel):
    """Initializes the ContextSummaryNode with a language model.

    Sets up the context summarizer with the necessary system prompts and
    logging configuration for processing retrieved context.

    Args:
      model: Language model instance that will be used for organizing and
        structuring context. Must be a BaseChatModel implementation
        suitable for detailed text processing and organization.
    """
    self.system_prompt = SystemMessage(self.SYS_PROMPT)
    self.model = model

    self._logger = logging.getLogger("prometheus.lang_graph.nodes.context_summary_node")

  def format_messages(self, context_messages: Sequence[BaseMessage]):
    """Formats a sequence of messages into a structured list.

    Converts different types of messages (Human, AI, Tool) into a consistently
    formatted list of strings, preserving the message source and content.

    Args:
      context_messages: Sequence of BaseMessage instances to be formatted.
        Can include HumanMessage, AIMessage, and ToolMessage types.

    Returns:
      List of formatted message strings, each prefixed with its source type.
    """
    formatted_messages = []
    for message in context_messages:
      if isinstance(message, HumanMessage):
        formatted_messages.append(f"Human message: {message.content}")
      elif isinstance(message, AIMessage):
        formatted_messages.append(f"Assistant message: {message.content}")
      elif isinstance(message, ToolMessage):
        formatted_messages.append(f"Tool message: {message.content}")
    return formatted_messages

  def format_human_message(self, query: str, context_messages: Sequence[BaseMessage]):
    """Creates a formatted message combining query and context.

    Combines the user query with formatted context messages into a single
    structured message for the language model.

    Args:
      query: User's original query string.
      context_messages: context_message generated by ContextProviderNode.

    Returns:
      HumanMessage instance containing the formatted query and context.
    """
    formatted_context_messages = self.format_messages(context_messages)
    human_message = HumanMessage(
      self.HUMAN_PROMPT.format(query=query, context="\n".join(formatted_context_messages))
    )
    return human_message

  def __call__(self, state: ContextProviderState):
    """Processes context state to generate organized summary.

    Takes the current context state, formats it into messages for the
    language model, and generates a comprehensive, well-structured
    summary of all relevant information.

    Args:
      state: Current state containing query and context messages.

    Returns:
      Dictionary that updates the state with the structured summary.
    """
    human_message = self.format_human_message(state["query"], state["context_messages"])
    self._logger.debug(f"human_message: {human_message}")
    message_history = [
      self.system_prompt,
      self.format_human_message(state["query"], state["context_messages"]),
    ]
    response = self.model.invoke(message_history)
    self._logger.debug(f"ContextSummaryNode response:\n{response}")
    return {"summary": response.content}
